version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: genomica_mysql
    environment:
      MYSQL_DATABASE: genomica_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: genomica_user
      MYSQL_PASSWORD: genomica_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - genomica_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: .
    container_name: genomica_service
    command: >
      sh -c "sleep 15 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=genomica_db
      - DB_USER=genomica_user
      - DB_PASSWORD=genomica_pass
      - DB_HOST=db
      - DB_PORT=3306
      - ALLOWED_HOSTS=localhost,127.0.0.1,genomica_service
    depends_on:
      db:
        condition: service_healthy
    networks:
      - genomica_network

volumes:
  mysql_data:

networks:
  genomica_network:
    driver: bridge
